import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const questions = [
  // HISTORIA DEL TANGO (~15)
  {
    statement: "¿En qué década se originó el tango como género musical y danza?",
    optionA: "Década de 1850",
    optionB: "Década de 1880",
    optionC: "Década de 1910",
    optionD: "Década de 1930",
    correctOption: "B",
    category: "historia",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿En qué barrio porteño se considera que nació el tango?",
    optionA: "Palermo",
    optionB: "Recoleta",
    optionC: "La Boca",
    optionD: "San Telmo",
    correctOption: "C",
    category: "historia",
    difficulty: "EASY",
  },
  {
    statement: '¿En qué año se compuso "El Entrerriano", considerado el primer tango criollo?',
    optionA: "1897",
    optionB: "1903",
    optionC: "1910",
    optionD: "1917",
    correctOption: "A",
    category: "historia",
    difficulty: "HARD",
  },
  {
    statement: "¿Qué día se celebra el Día Nacional del Tango en Argentina?",
    optionA: "24 de junio",
    optionB: "11 de diciembre",
    optionC: "25 de mayo",
    optionD: "9 de julio",
    correctOption: "B",
    category: "historia",
    difficulty: "EASY",
  },
  {
    statement: '¿Quién compuso "La Cumparsita", uno de los tangos más famosos del mundo?',
    optionA: "Carlos Gardel",
    optionB: "Enrique Santos Discépolo",
    optionC: "Gerardo Matos Rodríguez",
    optionD: "Ástor Piazzolla",
    correctOption: "C",
    category: "historia",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿En qué año fue declarado el tango Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO?",
    optionA: "2005",
    optionB: "2009",
    optionC: "2012",
    optionD: "2015",
    correctOption: "B",
    category: "historia",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Qué se conoce como la "Guardia Vieja" del tango?',
    optionA: "Los primeros tangos hasta los años 1920",
    optionB: "El tango de la década de 1950",
    optionC: "El tango electrónico",
    optionD: "Los tangos compuestos en Europa",
    correctOption: "A",
    category: "historia",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿En qué ciudad europea tuvo el tango una gran aceptación a principios del siglo XX?",
    optionA: "Londres",
    optionB: "Berlín",
    optionC: "París",
    optionD: "Roma",
    correctOption: "C",
    category: "historia",
    difficulty: "EASY",
  },
  {
    statement: '¿Qué periodo del tango se conoce como la "Época de Oro"?',
    optionA: "1900-1920",
    optionB: "1935-1955",
    optionC: "1960-1980",
    optionD: "1990-2010",
    correctOption: "B",
    category: "historia",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Cuál fue el primer tango cantado con letra que tuvo éxito masivo?",
    optionA: "La Cumparsita",
    optionB: "Caminito",
    optionC: "Mi Noche Triste",
    optionD: "El Choclo",
    correctOption: "C",
    category: "historia",
    difficulty: "HARD",
  },
  {
    statement: "¿En qué año murió Carlos Gardel en un accidente aéreo?",
    optionA: "1930",
    optionB: "1935",
    optionC: "1940",
    optionD: "1945",
    correctOption: "B",
    category: "historia",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿El tango tiene influencias musicales de qué género afroargentino?",
    optionA: "El malambo",
    optionB: "La chacarera",
    optionC: "El candombe",
    optionD: "La zamba",
    correctOption: "C",
    category: "historia",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿En qué país además de Argentina se considera al tango como patrimonio propio?",
    optionA: "Brasil",
    optionB: "Uruguay",
    optionC: "Chile",
    optionD: "Paraguay",
    correctOption: "B",
    category: "historia",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué presidente argentino prohibió las letras de tango con lunfardo en la radio?",
    optionA: "Hipólito Yrigoyen",
    optionB: "Juan Domingo Perón",
    optionC: "La dictadura militar de 1943",
    optionD: "Arturo Frondizi",
    correctOption: "C",
    category: "historia",
    difficulty: "HARD",
  },
  {
    statement: "¿Cuál es el nombre del arrabal porteño que inspiró infinidad de letras de tango?",
    optionA: "Pompeya",
    optionB: "Belgrano",
    optionC: "Caballito",
    optionD: "Puerto Madero",
    correctOption: "A",
    category: "historia",
    difficulty: "MEDIUM",
  },

  // ORQUESTAS TÍPICAS (~15)
  {
    statement: "¿Quién dirigía la orquesta típica que llevó el tango a su máxima expresión bailable?",
    optionA: "Osvaldo Pugliese",
    optionB: "Juan D'Arienzo",
    optionC: "Aníbal Troilo",
    optionD: "Carlos Di Sarli",
    correctOption: "B",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿A quién se le conoce como "El Rey del Compás"?',
    optionA: "Osvaldo Pugliese",
    optionB: "Carlos Di Sarli",
    optionC: "Juan D\'Arienzo",
    optionD: "Rodolfo Biagi",
    correctOption: "C",
    category: "orquestas",
    difficulty: "EASY",
  },
  {
    statement: '¿Qué orquesta típica era conocida como "La orquesta del pueblo"?',
    optionA: "Orquesta de Aníbal Troilo",
    optionB: "Orquesta de Osvaldo Pugliese",
    optionC: "Orquesta de Francisco Canaro",
    optionD: "Orquesta de Julio De Caro",
    correctOption: "B",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién era conocido como "El Señor del Tango" por la elegancia de su orquesta?',
    optionA: "Horacio Salgán",
    optionB: "Alfredo De Angelis",
    optionC: "Carlos Di Sarli",
    optionD: "Mariano Mores",
    correctOption: "C",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué orquesta se caracterizaba por el uso intenso del bandoneón en sus arreglos?",
    optionA: "Di Sarli",
    optionB: "D'Arienzo",
    optionC: "Troilo",
    optionD: "Canaro",
    correctOption: "C",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién fue el director de la orquesta conocida como "La yumba"?',
    optionA: "Juan D'Arienzo",
    optionB: "Osvaldo Pugliese",
    optionC: "Carlos Di Sarli",
    optionD: "Alfredo Gobbi",
    correctOption: "B",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué orquesta grabó más discos en la historia del tango?",
    optionA: "Juan D'Arienzo",
    optionB: "Francisco Canaro",
    optionC: "Osvaldo Pugliese",
    optionD: "Aníbal Troilo",
    correctOption: "B",
    category: "orquestas",
    difficulty: "HARD",
  },
  {
    statement: "¿Quién fue el pianista de Juan D'Arienzo durante la Época de Oro?",
    optionA: "Osvaldo Pugliese",
    optionB: "Horacio Salgán",
    optionC: "Rodolfo Biagi",
    optionD: "Carlos Di Sarli",
    correctOption: "C",
    category: "orquestas",
    difficulty: "HARD",
  },
  {
    statement: "¿Qué orquesta típica se destacó por su estilo melódico y romántico?",
    optionA: "D'Arienzo",
    optionB: "Pugliese",
    optionC: "Di Sarli",
    optionD: "Troilo",
    correctOption: "C",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién compuso el famoso tango "La Yumba"?',
    optionA: "Osvaldo Pugliese",
    optionB: "Aníbal Troilo",
    optionC: "Juan D'Arienzo",
    optionD: "Horacio Salgán",
    correctOption: "A",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Cuál de estos directores revolucionó el tango con elementos del jazz y la música clásica?",
    optionA: "Francisco Canaro",
    optionB: "Ástor Piazzolla",
    optionC: "Juan D'Arienzo",
    optionD: "Alfredo De Angelis",
    correctOption: "B",
    category: "orquestas",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué orquesta se caracterizaba por tocar perfectamente para bailar milonga?",
    optionA: "Pugliese",
    optionB: "Troilo",
    optionC: "D'Arienzo",
    optionD: "Salgán",
    correctOption: "C",
    category: "orquestas",
    difficulty: "EASY",
  },
  {
    statement: "¿Quién fue Julio De Caro en la historia del tango?",
    optionA: "Un cantor famoso",
    optionB: "Un violinista y director que innovó la orquesta típica",
    optionC: "Un bailarín del Abasto",
    optionD: "Un letrista de la Guardia Vieja",
    correctOption: "B",
    category: "orquestas",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué instrumento tocaba Aníbal Troilo?",
    optionA: "Piano",
    optionB: "Violín",
    optionC: "Bandoneón",
    optionD: "Contrabajo",
    correctOption: "C",
    category: "orquestas",
    difficulty: "EASY",
  },
  {
    statement: '¿A Aníbal Troilo se lo conocía con qué apodo?',
    optionA: "El Gordo",
    optionB: "Pichuco",
    optionC: "El Polaco",
    optionD: "El Morocho",
    correctOption: "B",
    category: "orquestas",
    difficulty: "EASY",
  },

  // CANTANTES (~12)
  {
    statement: '¿Quién es considerado "El Zorzal Criollo"?',
    optionA: "Hugo del Carril",
    optionB: "Roberto Goyeneche",
    optionC: "Carlos Gardel",
    optionD: "Edmundo Rivero",
    correctOption: "C",
    category: "cantantes",
    difficulty: "EASY",
  },
  {
    statement: '¿Qué cantor era conocido como "El Polaco"?',
    optionA: "Roberto Goyeneche",
    optionB: "Ángel Vargas",
    optionC: "Alberto Castillo",
    optionD: "Floreal Ruíz",
    correctOption: "A",
    category: "cantantes",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué cantor fue famoso por interpretar tangos con la orquesta de Aníbal Troilo?",
    optionA: "Alberto Echagüe",
    optionB: "Francisco Fiorentino",
    optionC: "Alberto Castillo",
    optionD: "Ángel Vargas",
    correctOption: "B",
    category: "cantantes",
    difficulty: "HARD",
  },
  {
    statement: '¿Quién interpretaba de manera magistral el tango "Sur"?',
    optionA: "Edmundo Rivero",
    optionB: "Roberto Goyeneche",
    optionC: "Carlos Gardel",
    optionD: "Julio Sosa",
    correctOption: "B",
    category: "cantantes",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Qué cantante es conocido como "El Varón del Tango"?',
    optionA: "Alberto Castillo",
    optionB: "Edmundo Rivero",
    optionC: "Julio Sosa",
    optionD: "Hugo del Carril",
    correctOption: "C",
    category: "cantantes",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Quién fue la cantante de tango más importante de la historia argentina?",
    optionA: "Libertad Lamarque",
    optionB: "Mercedes Sosa",
    optionC: "Tita Merello",
    optionD: "Adriana Varela",
    correctOption: "C",
    category: "cantantes",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Qué cantor fue conocido como "El Cantor de Buenos Aires"?',
    optionA: "Carlos Gardel",
    optionB: "Alberto Castillo",
    optionC: "Roberto Goyeneche",
    optionD: "Edmundo Rivero",
    correctOption: "A",
    category: "cantantes",
    difficulty: "EASY",
  },
  {
    statement: '¿Quién cantaba con D\'Arienzo los tangos "La Puñalada" y "Paciencia"?',
    optionA: "Alberto Echagüe",
    optionB: "Héctor Mauré",
    optionC: "Ángel Vargas",
    optionD: "Jorge Valdez",
    correctOption: "A",
    category: "cantantes",
    difficulty: "HARD",
  },
  {
    statement: "¿Qué cantante de tango también fue un exitoso actor de cine argentino?",
    optionA: "Julio Sosa",
    optionB: "Hugo del Carril",
    optionC: "Edmundo Rivero",
    optionD: "Alberto Morán",
    correctOption: "B",
    category: "cantantes",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué cantora de tango interpretaba el tema 'Malena'?",
    optionA: "Tita Merello",
    optionB: "Libertad Lamarque",
    optionC: "Susana Rinaldi",
    optionD: "Todas la interpretaron",
    correctOption: "D",
    category: "cantantes",
    difficulty: "HARD",
  },
  {
    statement: '¿Quién grabó por primera vez "Mi Buenos Aires querido"?',
    optionA: "Hugo del Carril",
    optionB: "Carlos Gardel",
    optionC: "Julio Sosa",
    optionD: "Edmundo Rivero",
    correctOption: "B",
    category: "cantantes",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué cantante moderno de tango es conocido internacionalmente y ganó un Grammy Latino?",
    optionA: "Adriana Varela",
    optionB: "Rubén Juárez",
    optionC: "Bajofondo",
    optionD: "Gotan Project",
    correctOption: "C",
    category: "cantantes",
    difficulty: "HARD",
  },

  // COMPOSITORES Y LETRISTAS (~12)
  {
    statement: '¿Quién compuso la letra de "Cambalache"?',
    optionA: "Homero Manzi",
    optionB: "Enrique Santos Discépolo",
    optionC: "Celedonio Flores",
    optionD: "Alfredo Le Pera",
    correctOption: "B",
    category: "compositores",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién fue el letrista de "Sur" y "Malena"?',
    optionA: "Celedonio Flores",
    optionB: "Enrique Cadícamo",
    optionC: "Homero Manzi",
    optionD: "Alfredo Le Pera",
    correctOption: "C",
    category: "compositores",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién compuso la música de "El Choclo"?',
    optionA: "Ángel Villoldo",
    optionB: "Juan de Dios Filiberto",
    optionC: "Enrique Delfino",
    optionD: "Francisco Canaro",
    correctOption: "A",
    category: "compositores",
    difficulty: "HARD",
  },
  {
    statement: '¿Quién fue el compositor de "Caminito"?',
    optionA: "Homero Manzi",
    optionB: "Juan de Dios Filiberto",
    optionC: "Mariano Mores",
    optionD: "Enrique Santos Discépolo",
    correctOption: "B",
    category: "compositores",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién compuso "Libertango"?',
    optionA: "Osvaldo Pugliese",
    optionB: "Mariano Mores",
    optionC: "Ástor Piazzolla",
    optionD: "Horacio Salgán",
    correctOption: "C",
    category: "compositores",
    difficulty: "EASY",
  },
  {
    statement: '¿Quién escribió la letra de "Uno"?',
    optionA: "Alfredo Le Pera",
    optionB: "Enrique Santos Discépolo",
    optionC: "Homero Manzi",
    optionD: "Cátulo Castillo",
    correctOption: "B",
    category: "compositores",
    difficulty: "HARD",
  },
  {
    statement: '¿Quién compuso "Adiós Nonino" en homenaje a su padre?',
    optionA: "Aníbal Troilo",
    optionB: "Ástor Piazzolla",
    optionC: "Osvaldo Pugliese",
    optionD: "Mariano Mores",
    correctOption: "B",
    category: "compositores",
    difficulty: "EASY",
  },
  {
    statement: '¿Quién fue Alfredo Le Pera?',
    optionA: "Un bandoneonista",
    optionB: "Un letrista que escribió con Gardel",
    optionC: "Un director de orquesta",
    optionD: "Un bailarín famoso",
    correctOption: "B",
    category: "compositores",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién compuso "Balada para un loco"?',
    optionA: "Pugliese y Manzi",
    optionB: "Piazzolla y Ferrer",
    optionC: "Troilo y Castillo",
    optionD: "Di Sarli y Contursi",
    correctOption: "B",
    category: "compositores",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién fue Pascual Contursi, autor de la letra de "Mi Noche Triste"?',
    optionA: "El primer gran letrista de tango",
    optionB: "Un director de orquesta",
    optionC: "Un bailarín de la Guardia Vieja",
    optionD: "Un pianista famoso",
    correctOption: "A",
    category: "letristas",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Quién compuso "Nostalgias"?',
    optionA: "Juan Carlos Cobián y Enrique Cadícamo",
    optionB: "Troilo y Manzi",
    optionC: "Di Sarli y Castillo",
    optionD: "Pugliese y Discépolo",
    correctOption: "A",
    category: "compositores",
    difficulty: "HARD",
  },
  {
    statement: '¿Quién es el autor de la letra de "Por una Cabeza"?',
    optionA: "Homero Manzi",
    optionB: "Celedonio Flores",
    optionC: "Alfredo Le Pera",
    optionD: "Enrique Cadícamo",
    correctOption: "C",
    category: "letristas",
    difficulty: "MEDIUM",
  },

  // INSTRUMENTOS (~8)
  {
    statement: "¿Cuál es el instrumento emblemático del tango?",
    optionA: "Guitarra",
    optionB: "Violín",
    optionC: "Bandoneón",
    optionD: "Piano",
    correctOption: "C",
    category: "instrumentos",
    difficulty: "EASY",
  },
  {
    statement: "¿De qué país es originario el bandoneón?",
    optionA: "Argentina",
    optionB: "Italia",
    optionC: "Francia",
    optionD: "Alemania",
    correctOption: "D",
    category: "instrumentos",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Cuántos botones tiene un bandoneón típico?",
    optionA: "52",
    optionB: "71",
    optionC: "38",
    optionD: "100",
    correctOption: "B",
    category: "instrumentos",
    difficulty: "HARD",
  },
  {
    statement: "¿Cuáles son los instrumentos de la orquesta típica de tango?",
    optionA: "Bandoneones, violines, piano, contrabajo",
    optionB: "Guitarra, flauta, charango, bombo",
    optionC: "Saxo, trompeta, batería, bajo",
    optionD: "Acordeón, guitarra, violín, flauta",
    correctOption: "A",
    category: "instrumentos",
    difficulty: "EASY",
  },
  {
    statement: "¿Quién inventó el bandoneón?",
    optionA: "Carlos Gardel",
    optionB: "Heinrich Band",
    optionC: "Ástor Piazzolla",
    optionD: "Carl Zimmermann",
    correctOption: "B",
    category: "instrumentos",
    difficulty: "HARD",
  },
  {
    statement: "¿Para qué se usaba originalmente el bandoneón en Alemania?",
    optionA: "En orquestas sinfónicas",
    optionB: "En música religiosa en iglesias pequeñas",
    optionC: "Como instrumento militar",
    optionD: "En fiestas populares bávaras",
    correctOption: "B",
    category: "instrumentos",
    difficulty: "HARD",
  },
  {
    statement: "¿Qué rol cumple el contrabajo en la orquesta típica de tango?",
    optionA: "La melodía principal",
    optionB: "Solo de improvisación",
    optionC: "La base rítmica y armónica",
    optionD: "Acompañamiento vocal",
    correctOption: "C",
    category: "instrumentos",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué marca de bandoneón es la más buscada por los tangueros?",
    optionA: "Yamaha",
    optionB: "AA (Alfred Arnold)",
    optionC: "Hohner",
    optionD: "Roland",
    correctOption: "B",
    category: "instrumentos",
    difficulty: "HARD",
  },

  // CÓDIGOS DE MILONGA (~10)
  {
    statement: "¿Qué es la 'cabeceo' en una milonga?",
    optionA: "Un paso de baile",
    optionB: "Un saludo formal al entrar",
    optionC: "La invitación a bailar con la mirada y un gesto de cabeza",
    optionD: "El nombre del DJ de tango",
    correctOption: "C",
    category: "codigos",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué es una 'tanda' en una milonga?",
    optionA: "Un tipo de zapato de tango",
    optionB: "Un grupo de 3-4 tangos seguidos para bailar con la misma pareja",
    optionC: "El nombre del escenario",
    optionD: "Una figura de baile avanzada",
    correctOption: "B",
    category: "codigos",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué es la 'cortina' en una milonga?",
    optionA: "La tela que decora el salón",
    optionB: "El telón del escenario",
    optionC: "La música corta entre tandas que indica cambio de pareja",
    optionD: "El cierre de la milonga",
    correctOption: "C",
    category: "codigos",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿En qué sentido se circula en la pista de baile de una milonga?",
    optionA: "En sentido horario",
    optionB: "En sentido antihorario",
    optionC: "En cualquier sentido",
    optionD: "No hay regla de circulación",
    correctOption: "B",
    category: "codigos",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué significa 'ronda' en el contexto de la milonga?",
    optionA: "Una bebida de cortesía",
    optionB: "La circulación ordenada de las parejas en la pista",
    optionC: "Un estilo de tango",
    optionD: "Un tipo de calzado",
    correctOption: "B",
    category: "codigos",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué es el 'mirada y cabeceo'?",
    optionA: "Un paso de ochos",
    optionB: "El sistema tradicional de invitación al baile",
    optionC: "Un adorno del hombre",
    optionD: "Una secuencia coreográfica",
    correctOption: "B",
    category: "codigos",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué NO se debe hacer en la pista de una milonga tradicional?",
    optionA: "Bailar en abrazo cerrado",
    optionB: "Hacer figuras que molesten a otras parejas",
    optionC: "Seguir la línea de baile",
    optionD: "Respetar la ronda",
    correctOption: "B",
    category: "codigos",
    difficulty: "EASY",
  },
  {
    statement: "¿Cuántos tangos suele tener una tanda?",
    optionA: "2",
    optionB: "3 o 4",
    optionC: "6",
    optionD: "10",
    correctOption: "B",
    category: "codigos",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué significa cuando suena la cortina en una milonga?",
    optionA: "Continuar bailando",
    optionB: "Aplaudir al DJ",
    optionC: "Agradecer a tu pareja y volver al asiento",
    optionD: "Cambiar de estilo de baile",
    correctOption: "C",
    category: "codigos",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué es el 'musicalizador' o 'DJ de tango'?",
    optionA: "Quien toca el bandoneón en vivo",
    optionB: "Quien selecciona y organiza la música en tandas y cortinas",
    optionC: "El dueño del salón",
    optionD: "Quien enseña los pasos antes de la milonga",
    correctOption: "B",
    category: "codigos",
    difficulty: "MEDIUM",
  },

  // TANGO DANZA (~10)
  {
    statement: "¿Cuáles son los tres ritmos que se bailan en una milonga?",
    optionA: "Tango, salsa y cumbia",
    optionB: "Tango, vals y milonga",
    optionC: "Tango, folklore y rock",
    optionD: "Tango, candombe y murga",
    correctOption: "B",
    category: "danza",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué es el 'ocho' en el tango?",
    optionA: "El número de tangos por tanda",
    optionB: "Una figura donde los pies dibujan un ocho en el piso",
    optionC: "Ocho compases musicales",
    optionD: "Un tipo de calzado",
    correctOption: "B",
    category: "danza",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué diferencia al tango de salón del tango escenario?",
    optionA: "La música que se usa",
    optionB: "El salón usa figuras más espectaculares",
    optionC: "El escenario incluye figuras acrobáticas y coreográficas no bailables en milonga",
    optionD: "No hay diferencia",
    correctOption: "C",
    category: "danza",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué es la 'caminata' en el tango?",
    optionA: "Ir a comprar zapatos de tango",
    optionB: "El paso básico y fundamental del tango",
    optionC: "Un tipo de tango rápido",
    optionD: "El recorrido al salón de milonga",
    correctOption: "B",
    category: "danza",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué significa 'abrazo abierto' en el tango?",
    optionA: "No abrazar a la pareja",
    optionB: "Un abrazo con espacio entre los cuerpos, permitiendo figuras",
    optionC: "Bailar sin contacto físico",
    optionD: "Un abrazo grupal",
    correctOption: "B",
    category: "danza",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué es un 'gancho' en el tango?",
    optionA: "El precio de la entrada a la milonga",
    optionB: "Una figura donde la pierna engancha la del compañero",
    optionC: "Un instrumento musical",
    optionD: "El nombre de un tango famoso",
    correctOption: "B",
    category: "danza",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué es la 'sacada' en el tango?",
    optionA: "Sacar a alguien de la pista",
    optionB: "Una figura donde un bailarín desplaza el pie del otro con su pierna",
    optionC: "El final de la milonga",
    optionD: "Una bebida del buffet",
    correctOption: "B",
    category: "danza",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Quién lidera el baile en el tango tradicional?",
    optionA: "El musicalizador",
    optionB: "La mujer",
    optionC: "El hombre",
    optionD: "Ambos por igual",
    correctOption: "C",
    category: "danza",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué es el 'volcán' o 'volcada' en el tango?",
    optionA: "Cuando el bailarín se cae",
    optionB: "Una figura donde la mujer se inclina hacia su pareja con el eje compartido",
    optionC: "Un tango muy rápido",
    optionD: "El calentamiento previo al baile",
    correctOption: "B",
    category: "danza",
    difficulty: "HARD",
  },
  {
    statement: "¿Qué es el 'boleo' en el tango?",
    optionA: "Una figura donde la pierna sube por efecto de un giro o cambio de dirección",
    optionB: "Golpear el piso con el pie",
    optionC: "Una forma de saludar",
    optionD: "El nombre de un estilo de tango",
    correctOption: "A",
    category: "danza",
    difficulty: "MEDIUM",
  },

  // CULTURA TANGUERA (~8)
  {
    statement: "¿Qué es el 'lunfardo'?",
    optionA: "Un barrio de Buenos Aires",
    optionB: "Una jerga usada en las letras de tango, originaria del Río de la Plata",
    optionC: "Un instrumento musical",
    optionD: "Un estilo de baile",
    correctOption: "B",
    category: "cultura",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué significa 'mina' en lunfardo?",
    optionA: "Una mina de oro",
    optionB: "Mujer",
    optionC: "Un barrio",
    optionD: "Un tango famoso",
    correctOption: "B",
    category: "cultura",
    difficulty: "EASY",
  },
  {
    statement: '¿Qué significa "afanar" en lunfardo?',
    optionA: "Trabajar duro",
    optionB: "Bailar bien",
    optionC: "Robar",
    optionD: "Comer mucho",
    correctOption: "C",
    category: "cultura",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué es el 'fileteado porteño'?",
    optionA: "Un corte de carne típico",
    optionB: "Un arte decorativo porteño con colores vivos y diseños florales",
    optionC: "Un paso de tango",
    optionD: "Un estilo de canto",
    correctOption: "B",
    category: "cultura",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Qué café porteño es emblemático del tango?",
    optionA: "Starbucks Recoleta",
    optionB: "Café Tortoni",
    optionC: "Café Martínez",
    optionD: "Havanna",
    correctOption: "B",
    category: "cultura",
    difficulty: "EASY",
  },
  {
    statement: '¿Qué significa "garúa" en el tango?',
    optionA: "Una garza",
    optionB: "Llovizna fina y persistente",
    optionC: "Un barrio lejano",
    optionD: "Un giro del baile",
    correctOption: "B",
    category: "cultura",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Qué significa "bulín" en lunfardo?',
    optionA: "Un restaurant",
    optionB: "Un departamento pequeño, cuarto de soltero",
    optionC: "Un automóvil",
    optionD: "Un sombrero",
    correctOption: "B",
    category: "cultura",
    difficulty: "MEDIUM",
  },
  {
    statement: '¿Qué es un "conventillo" en la cultura del tango?',
    optionA: "Un convento religioso",
    optionB: "Una casa colectiva donde vivían inmigrantes, cuna del tango",
    optionC: "Un tipo de musical",
    optionD: "Un teatro de tango",
    correctOption: "B",
    category: "cultura",
    difficulty: "MEDIUM",
  },

  // CIUDADES Y FESTIVALES (~5)
  {
    statement: "¿En qué ciudad se realiza el Mundial de Tango?",
    optionA: "Montevideo",
    optionB: "Buenos Aires",
    optionC: "Medellín",
    optionD: "París",
    correctOption: "B",
    category: "ciudades",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué festival de tango se realiza en Comodoro Rivadavia?",
    optionA: "Tango Buenos Aires",
    optionB: "Festival Nacional del Tango",
    optionC: "Vientos de Tango",
    optionD: "Tango del Sur",
    correctOption: "C",
    category: "ciudades",
    difficulty: "EASY",
  },
  {
    statement: "¿En qué calle de Buenos Aires hay un famoso paseo del tango?",
    optionA: "Avenida 9 de Julio",
    optionB: "Caminito en La Boca",
    optionC: "Calle Florida",
    optionD: "Avenida Corrientes",
    correctOption: "B",
    category: "ciudades",
    difficulty: "EASY",
  },
  {
    statement: "¿Qué barrio de Buenos Aires está asociado a Carlos Gardel?",
    optionA: "San Telmo",
    optionB: "Palermo",
    optionC: "El Abasto",
    optionD: "Barracas",
    correctOption: "C",
    category: "ciudades",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿En qué categorías se compite en el Mundial de Tango?",
    optionA: "Solo masculino y solo femenino",
    optionB: "Tango pista y tango escenario",
    optionC: "Milonga y vals solamente",
    optionD: "Individual y grupal",
    correctOption: "B",
    category: "ciudades",
    difficulty: "MEDIUM",
  },

  // CURIOSIDADES (~5)
  {
    statement: "¿En qué película de Hollywood aparece el tango 'Por una Cabeza'?",
    optionA: "El Padrino",
    optionB: "Perfume de Mujer (Scent of a Woman)",
    optionC: "Titanic",
    optionD: "Rocky",
    correctOption: "B",
    category: "curiosidades",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Cuál fue el primer tango grabado en un disco?",
    optionA: "La Cumparsita",
    optionB: "El Choclo",
    optionC: "Don Juan",
    optionD: "Mi Noche Triste",
    correctOption: "C",
    category: "curiosidades",
    difficulty: "HARD",
  },
  {
    statement: "¿Originalmente, quiénes bailaban tango entre sí?",
    optionA: "Solo mujeres",
    optionB: "Hombres entre hombres para practicar",
    optionC: "Solo la clase alta",
    optionD: "Solo en teatros",
    correctOption: "B",
    category: "curiosidades",
    difficulty: "MEDIUM",
  },
  {
    statement: "¿Cuál es la nacionalidad más debatida de Carlos Gardel?",
    optionA: "Italiano o español",
    optionB: "Argentino o uruguayo",
    optionC: "Francés o argentino",
    optionD: "Brasileño o argentino",
    correctOption: "C",
    category: "curiosidades",
    difficulty: "HARD",
  },
  {
    statement: "¿Qué tango fue el primero en ser escuchado en el espacio exterior?",
    optionA: "Libertango",
    optionB: "La Cumparsita",
    optionC: "Por una Cabeza",
    optionD: "Ninguno llegó al espacio",
    correctOption: "C",
    category: "curiosidades",
    difficulty: "HARD",
  },
]

async function seedTriviaQuestions() {
  console.log("🎭 Seeding 100 tango trivia questions...")

  // Create game config if it doesn't exist
  const existingGame = await prisma.triviaGame.findFirst({
    where: { name: "Acertijo 2.0" },
  })

  if (!existingGame) {
    await prisma.triviaGame.create({
      data: {
        name: "Acertijo 2.0",
        isActive: false,
        questionsPerGame: 10,
        timePerQuestion: 30,
        pointsCorrect: 10,
        pointsIncorrect: 0,
      },
    })
    console.log("✅ Game config created")
  }

  // Check existing questions
  const existingCount = await prisma.triviaQuestion.count()
  if (existingCount > 0) {
    console.log(`⚠ Already ${existingCount} questions in DB. Skipping seed.`)
    return
  }

  // Insert all questions
  for (const q of questions) {
    await prisma.triviaQuestion.create({ data: q })
  }

  console.log(`✅ ${questions.length} questions seeded successfully!`)

  // Print category distribution
  const categories = questions.reduce((acc, q) => {
    acc[q.category] = (acc[q.category] || 0) + 1
    return acc
  }, {} as Record<string, number>)

  console.log("\n📊 Distribution by category:")
  Object.entries(categories)
    .sort((a, b) => b[1] - a[1])
    .forEach(([cat, count]) => {
      console.log(`   ${cat}: ${count}`)
    })

  const difficulties = questions.reduce((acc, q) => {
    acc[q.difficulty] = (acc[q.difficulty] || 0) + 1
    return acc
  }, {} as Record<string, number>)

  console.log("\n📊 Distribution by difficulty:")
  Object.entries(difficulties).forEach(([diff, count]) => {
    console.log(`   ${diff}: ${count}`)
  })
}

seedTriviaQuestions()
  .then(() => {
    console.log("\n🎉 Trivia seed completed!")
    process.exit(0)
  })
  .catch((e) => {
    console.error("Seed failed:", e)
    process.exit(1)
  })
